### ISSUE TITLE
AssertionError with `test_cov_matrix_diag` function

### ISSUE THREAD

**Issue by jennifer-hoang** [UBC-MDS/EDAhelper#66]
Hi @Rowansiv,

I found a small error with the test_cov_matrix_diag function when running pytest (screenshot below). I think we might need to add a tolerance to the assert statement for the test to pass. Would you be able to look into this?

Thank you!

![Screen Shot 2022-01-26 at 7 04 34 PM](https://user-images.githubusercontent.com/94317883/151284775-158e0974-ab37-47fb-84f7-33890bf9eee8.png)

**Comment by Rowansiv** [comment]
I've fixed this now @jennifer-hoang , please let me know if it still doesn't work. Thanks!
