### ISSUE TITLE
Tests: Add test cases for column_stats to test the data validations.

### ISSUE THREAD

**Issue by stevenleung2018** [UBC-MDS/EDAhelper#72]
Hi Rowan,

Please check this out:

https://app.codecov.io/gh/UBC-MDS/EDAhelper/blob/master/src/EDAhelper/column_stats.py

The red ones are the lines not covered by any tests.  I have checked your test script and found that they are really not covered.  Can you add test cases?  Then we can have 100% test coverage.

Thanks.

Regards,

Steven

**Comment by stevenleung2018** [comment]
Just for the avoidance of doubt, if your code is checking that the `columns` argument should be a list, tuple or array, then your test case should be try to pass a number to it, and `column_stats` should throw an error.

**Comment by Rowansiv** [comment]
Completed writing new test cases, reviewed by Steven
